services:
  db:
    image: postgres:17.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: java_be_genai_plgrnd
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -D java_be_genai_plgrnd" ]
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
    build: ./
    depends_on:
      - db
    expose:
      - "3002"
    ports:
      - "3002:3002"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: root
  react_frontend:
    build: ../sports_hub_react_skeleton
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      REACT_APP_API_URL: "http://localhost:3002"

volumes:
  postgres_data:
