CREATE EXTENSION pgcrypto;

CREATE TABLE article
(
    id                      UUID            DEFAULT gen_random_uuid(),
    title                   VARCHAR(255)    NOT NULL,
    short_description       VARCHAR(255)    NOT NULL,
    description             TEXT            NOT NULL,
    creation_timestamp      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update_timestamp   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT unique_title UNIQUE (title)
);

CREATE TABLE comment
(
    id                      UUID            DEFAULT gen_random_uuid(),
    article_id              UUID            NOT NULL,
    content                 TEXT            NOT NULL,
    creation_timestamp      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update_timestamp   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (article_id) REFERENCES article(id)
);

INSERT INTO article (title, short_description, description) VALUES
    ('The Rise of Soccer', 'A look at soccer''s global popularity', 'Soccer has become the most popular sport in the world, with millions of fans. It is played in almost every country and has a rich history.'),
    ('Basketball Legends', 'Profiles of the greatest basketball players', 'From Michael Jordan to LeBron James, basketball has seen some of the greatest athletes. Their impact on the sport is immeasurable.'),
    ('Olympic Games History', 'The evolution of the Olympic Games', 'The Olympic Games have a rich history dating back to ancient Greece. They have evolved significantly over the centuries.'),
    ('The World of Tennis', 'An overview of professional tennis', 'Tennis is a sport that requires agility, strength, and strategy. It is played on various surfaces and has a global following.'),
    ('Marathon Running', 'The challenge of marathon running', 'Running a marathon is a test of endurance and mental strength. It requires months of training and preparation.'),
    ('The NFL Experience', 'Inside the National Football League', 'The NFL is one of the most popular sports leagues in the United States. It features intense competition and passionate fans.'),
    ('Cricket: A Global Sport', 'Cricket''s impact around the world', 'Cricket is a sport that has a massive following in countries like India and Australia. It is known for its long matches and strategic play.'),
    ('The Art of Gymnastics', 'The beauty and skill of gymnastics', 'Gymnastics is a sport that combines strength, flexibility, and grace. It is performed on various apparatus and requires years of training.'),
    ('Formula 1 Racing', 'The thrill of Formula 1', 'Formula 1 racing is a high-speed sport that requires precision and skill. It features some of the fastest cars and most talented drivers.'),
    ('The World of Rugby', 'Rugby''s global influence', 'Rugby is a sport that is known for its physicality and teamwork. It is played in many countries and has a passionate fan base.'),
    ('Golf: A Gentleman''s Game', 'The traditions of golf', 'Golf is a sport that is steeped in tradition and requires skill and patience. It is played on beautifully manicured courses around the world.'),
    ('The Evolution of Baseball', 'Baseball''s history and impact', 'Baseball is a sport that has a rich history in the United States. It is known as America''s pastime and has a significant cultural impact.'),
    ('The World of Boxing', 'The intensity of boxing', 'Boxing is a sport that requires strength, strategy, and endurance. It has produced some of the most famous athletes in history.'),
    ('The Spirit of Volleyball', 'Volleyball''s popularity and rules', 'Volleyball is a sport that is enjoyed by millions around the world. It is played both indoors and on the beach.'),
    ('The World of Swimming', 'Competitive swimming insights', 'Swimming is a sport that requires speed, technique, and endurance. It is a popular event in the Olympic Games.'),
    ('The World of Hockey', 'Ice hockey''s global reach', 'Hockey is a sport that is known for its speed and physicality. It is played on ice and has a strong following in countries like Canada.'),
    ('The World of Surfing', 'The culture of surfing', 'Surfing is a sport that is enjoyed by many for its connection to the ocean. It requires balance, skill, and a love for the waves.'),
    ('The World of Skiing', 'Skiing''s appeal and techniques', 'Skiing is a sport that is enjoyed by many for its thrill and challenge. It is performed on snow-covered slopes and requires skill and practice.'),
    ('The World of Snowboarding', 'Snowboarding''s rise in popularity', 'Snowboarding is a sport that has gained popularity for its excitement and style. It is performed on snow-covered slopes and requires balance and skill.'),
    ('The World of Cycling', 'Competitive cycling insights', 'Cycling is a sport that requires endurance, strategy, and teamwork. It is performed on various terrains and has a global following.');

INSERT INTO comment (article_id, content) VALUES
    ((SELECT id FROM article WHERE title = 'The Rise of Soccer'), 'Soccer is truly a global phenomenon.'),
    ((SELECT id FROM article WHERE title = 'The Rise of Soccer'), 'I love watching soccer matches on weekends.'),
    ((SELECT id FROM article WHERE title = 'Basketball Legends'), 'Michael Jordan is the greatest of all time.'),
    ((SELECT id FROM article WHERE title = 'Basketball Legends'), 'LeBron James has had an incredible career.'),
    ((SELECT id FROM article WHERE title = 'Olympic Games History'), 'The history of the Olympics is fascinating.'),
    ((SELECT id FROM article WHERE title = 'Olympic Games History'), 'I enjoy watching the opening ceremonies.'),
    ((SELECT id FROM article WHERE title = 'The World of Tennis'), 'Tennis matches are so intense and exciting.'),
    ((SELECT id FROM article WHERE title = 'The World of Tennis'), 'Roger Federer is my favorite tennis player.'),
    ((SELECT id FROM article WHERE title = 'Marathon Running'), 'Running a marathon is a huge accomplishment.'),
    ((SELECT id FROM article WHERE title = 'Marathon Running'), 'I am training for my first marathon.'),
    ((SELECT id FROM article WHERE title = 'The NFL Experience'), 'The NFL playoffs are always thrilling.'),
    ((SELECT id FROM article WHERE title = 'The NFL Experience'), 'I am a big fan of the New England Patriots.'),
    ((SELECT id FROM article WHERE title = 'Cricket: A Global Sport'), 'Cricket matches can last for days.'),
    ((SELECT id FROM article WHERE title = 'Cricket: A Global Sport'), 'I love watching cricket with my family.'),
    ((SELECT id FROM article WHERE title = 'The Art of Gymnastics'), 'Gymnastics requires incredible skill and strength.'),
    ((SELECT id FROM article WHERE title = 'The Art of Gymnastics'), 'The balance beam is my favorite event.'),
    ((SELECT id FROM article WHERE title = 'Formula 1 Racing'), 'Formula 1 races are so fast and exciting.'),
    ((SELECT id FROM article WHERE title = 'Formula 1 Racing'), 'Lewis Hamilton is an amazing driver.'),
    ((SELECT id FROM article WHERE title = 'The World of Rugby'), 'Rugby is such a physical and demanding sport.'),
    ((SELECT id FROM article WHERE title = 'The World of Rugby'), 'I enjoy watching the Rugby World Cup.'),
    ((SELECT id FROM article WHERE title = 'Golf: A Gentleman''s Game'), 'Golf courses are always so beautiful.'),
    ((SELECT id FROM article WHERE title = 'Golf: A Gentleman''s Game'), 'Tiger Woods is a legendary golfer.'),
    ((SELECT id FROM article WHERE title = 'The Evolution of Baseball'), 'Baseball has a rich and storied history.'),
    ((SELECT id FROM article WHERE title = 'The Evolution of Baseball'), 'I love going to baseball games in the summer.'),
    ((SELECT id FROM article WHERE title = 'The World of Boxing'), 'Boxing matches are so intense and thrilling.'),
    ((SELECT id FROM article WHERE title = 'The World of Boxing'), 'Muhammad Ali is the greatest boxer of all time.'),
    ((SELECT id FROM article WHERE title = 'The Spirit of Volleyball'), 'Volleyball is a fun and fast-paced sport.'),
    ((SELECT id FROM article WHERE title = 'The Spirit of Volleyball'), 'I enjoy playing beach volleyball with friends.'),
    ((SELECT id FROM article WHERE title = 'The World of Swimming'), 'Swimming is a great way to stay in shape.'),
    ((SELECT id FROM article WHERE title = 'The World of Swimming'), 'Michael Phelps is an incredible swimmer.'),
    ((SELECT id FROM article WHERE title = 'The World of Hockey'), 'Hockey games are so fast and exciting.'),
    ((SELECT id FROM article WHERE title = 'The World of Hockey'), 'I am a big fan of the Toronto Maple Leafs.'),
    ((SELECT id FROM article WHERE title = 'The World of Surfing'), 'Surfing is such a cool and laid-back sport.'),
    ((SELECT id FROM article WHERE title = 'The World of Surfing'), 'I would love to learn how to surf.'),
    ((SELECT id FROM article WHERE title = 'The World of Skiing'), 'Skiing down a mountain is so exhilarating.'),
    ((SELECT id FROM article WHERE title = 'The World of Skiing'), 'I enjoy skiing with my family every winter.'),
    ((SELECT id FROM article WHERE title = 'The World of Snowboarding'), 'Snowboarding is such a fun and exciting sport.'),
    ((SELECT id FROM article WHERE title = 'The World of Snowboarding'), 'I love watching snowboarding competitions.'),
    ((SELECT id FROM article WHERE title = 'The World of Cycling'), 'Cycling is a great way to explore the outdoors.'),
    ((SELECT id FROM article WHERE title = 'The World of Cycling'), 'I enjoy going on long bike rides on weekends.'),
    ((SELECT id FROM article WHERE title = 'The Rise of Soccer'), 'The World Cup is the biggest event in soccer.'),
    ((SELECT id FROM article WHERE title = 'Basketball Legends'), 'Kobe Bryant was an incredible player.'),
    ((SELECT id FROM article WHERE title = 'Olympic Games History'), 'The Olympic Games bring the world together.'),
    ((SELECT id FROM article WHERE title = 'The World of Tennis'), 'The Wimbledon tournament is my favorite.'),
    ((SELECT id FROM article WHERE title = 'Marathon Running'), 'Running a marathon is a true test of endurance.'),
    ((SELECT id FROM article WHERE title = 'The NFL Experience'), 'The Super Bowl is the biggest event in the NFL.'),
    ((SELECT id FROM article WHERE title = 'Cricket: A Global Sport'), 'Cricket is a sport that requires strategy and skill.'),
    ((SELECT id FROM article WHERE title = 'The Art of Gymnastics'), 'Gymnastics routines are so beautiful to watch.'),
    ((SELECT id FROM article WHERE title = 'Formula 1 Racing'), 'Formula 1 cars are incredibly fast and powerful.'),
    ((SELECT id FROM article WHERE title = 'The World of Rugby'), 'Rugby matches are always so intense and exciting.');